### ISSUE TITLE
[BUG] createAction and ofHub

### ISSUE THREAD

**Issue by AlexChar** [Odonno/ngrx-signalr#1]
First of all thanks a lot for sharing this code but I have some issues using your package.

I'm using latests @ngrx and more specific:

```
    "@ngrx/effects": "^7.4.0",
    "@ngrx/entity": "^7.4.0",
    "@ngrx/router-store": "^7.4.0",
    "@ngrx/store": "^7.4.0",
```

In the following code:

```
@Effect()
  initHubOne$ = this.actions$.pipe(
    ofType<SignalRHubUnstartedAction>(SIGNALR_HUB_UNSTARTED),
    ofHub('hub1'),
    mergeMap<SignalRHubUnstartedAction, any>(action => {
      // TODO : init hub 1
      const hub = findHub(action);

      const whenEvent$ = hub.on('eventName').pipe(map(x => createAction(x)));

      return merge(whenEvent$, of(startSignalRHub(action.hubName, action.url)));
    })
  );
```

this line```const whenEvent$ = hub.on('eventName').pipe(map(x => createAction(x)));``` 

```
Argument of type 'import("c:/dev/ariadne/admin-fe/node_modules/rxjs/internal/types").OperatorFunction<{}, any>' is not assignable to parameter of type 'import("c:/dev/ariadne/admin-fe/node_modules/ngrx-signalr/node_modules/rxjs/internal/types").OperatorFunction<{}, any>'.
  Types of parameters 'source' and 'source' are incompatible.
    Property 'delay' is missing in type 'Observable<{}>' but required in type 'Observable<{}>'.ts(2345)
delay.d.ts(4, 9): 'delay' is declared here.
```

Also ```Cannot find name 'ofHub'```

**Comment by Odonno** [comment]
Hello @AlexChar 

Before all, have you followed the instructions here ? https://github.com/Odonno/ngrx-signalr#install-dependencies

If you do, can you provide the complete `package.json`? I do not know why you got this error right now.

**Comment by AlexChar** [comment]
Yes I installed all of them(assume is a problem on latest ngrx version). My package.json

```
  "dependencies": {
    "@angular/animations": "^7.2.7",
    "@angular/common": "^7.2.7",
    "@angular/compiler": "^7.2.7",
    "@angular/compiler-cli": "^7.2.7",
    "@angular/core": "^7.2.7",
    "@angular/forms": "^7.2.7",
    "@angular/http": "^7.2.7",
    "@angular/platform-browser": "^7.2.7",
    "@angular/platform-browser-dynamic": "^7.2.7",
    "@angular/router": "^7.2.7",
    "@angularclass/hmr": "^2.1.3",
    "@aspnet/signalr": "^1.0.4",
    "@auth0/angular-jwt": "^2.0.0",
    "@ngrx/effects": "^7.4.0",
    "@ngrx/entity": "^7.4.0",
    "@ngrx/router-store": "^7.4.0",
    "@ngrx/store": "^7.4.0",
    "@ngrx/store-devtools": "^7.4.0",
    "core-js": "^2.5.5",
    "eslint-scope": "4.0.0",
    "flag-icon-css": "^3.0.0",
    "jquery": "^3.4.0",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "ngrx-signalr": "^2.0.18",
    "ngrx-store-freeze": "^0.2.2",
    "ngx-bootstrap": "^2.0.4",
    "primeicons": "^1.0.0",
    "primeng": "^7.0.0",
    "rxjs": "^6.5.1",
    "rxjs-compat": "^6.1.0",
    "ts-action": "^6.0.2",
    "ts-action-operators": "^7.0.0",
    "zone.js": "^0.8.29"
  },
 ```

Also I have a problem with the url. For example my hub url is:

```
/hub/signalrdummyonehub'
```

but when I use:

```
this.store.dispatch(createSignalRHub('signalrdummyonehub', 'hub/signalrdummyonehub'));
```

tries connect to
```
http://localhost:4202/hub/signalrdummyonehub/signalr/negotiate?clientProtocol=2.1&connectionData=%5B%7B%22name%22%3A%22signalrdummyonehub%22%7D%5D&_=1556112436270 404 (Not Found)
```
but the correct one is:
```
http://localhost:4202/hub/signalrdummyonehub
```

Thanks in advance.

**Comment by Odonno** [comment]
Oh. Well, it seems that you are using SignalR for ASP.NET Core. My current implementation is for the older version of SignalR (ASP.NET Framework).

It is so because I can see in your package.json that you added `@aspnet/signalr` instead of `signalr`.

So, before you ask, there is currently no plan to support SignalR "Core" right now but I suppose it is feasible if I split my code into two separate package like `ngrx-signalr` and `ngrx-signalr-aspnetcore`.

BTW, you don't need jQuery anymore for the ASP.NET Core version.

**Comment by AlexChar** [comment]
Thanks a lot for your responses @Odonno. I'm closing this issue.

**Comment by Odonno** [comment]
Hi @AlexChar 

I wanted to get back to you because I have recently ported this repository using SignalR .NET Framework to SignalR .NET Core.

You can find this new library here : https://github.com/Odonno/ngrx-signalr-core

It is pretty much the same library but with small differences : 
* using signalr dotnet core package obviously
* disconnecting and reconnecting states does not exist anymore
* creating a hub is a little different and you can provide a different `options` object
* handling reconnection is on you now (you need to create an effect by yourself but it also gives you more control over the reconnection strategy)

I don't know if you still need it but I hope it will useful for other developers.

BTW, I will try to avoid future confusion about .NET Framework/Core by updating the readme files.

**Comment by AlexChar** [comment]
Hi David,

Thanks a lot for your response! I have created my own implementation(in the
future I have plans to publish it on github) but for sure it will help
other developers!

Best,

Alex.

Στις Τρί, 28 Μαΐ 2019 στις 10:02 μ.μ., ο/η David Bottiau <
notifications@github.com> έγραψε:

**Comment by Odonno** [comment]
@AlexChar Nice. I would like to see how you made it.
